export const data = [
  {
    id: 1,
    foodName: "Artichokes - Knobless, White",
    price: 3625,
    img: "./first.png",
    categoryName: "Temp Fencing, Decorative Fencing and Gates",
  },
  {
    id: 2,
    foodName: "Pastry - Lemon Danish - Mini",
    price: 5249,
    img: "./second.png",
    categoryName: "Plumbing & Medical Gas",
  },
  {
    id: 3,
    foodName: "Olives - Black, Pitted",
    price: 5979,
    img: "./third.png",
    categoryName: "Asphalt Paving",
  },
  {
    id: 4,
    foodName: "Bread - Focaccia Quarter",
    price: 3126,
    img: "./forth.png",
    categoryName: "Soft Flooring and Base",
  },
  {
    id: 5,
    foodName: "Juice - Orangina",
    price: 3920,
    img: "./5.png",
    categoryName: "Exterior Signage",
  },
  {
    id: 6,
    foodName: "Parsnip",
    price: 8351,
    img: "./6.png",
    categoryName: "Wall Protection",
  },
  {
    id: 7,
    foodName: "Onion Powder",
    price: 7974,
    img: "./7.png",
    categoryName: "Roofing (Asphalt)",
  },
  {
    id: 8,
    foodName: "Goat - Whole Cut",
    price: 6446,
    img: "./8.png",
    categoryName: "Drywall & Acoustical (MOB)",
  },
  {
    id: 9,
    foodName: "Soup - Knorr, Ministrone",
    price: 9383,
    img: "./9.png",
    categoryName: "Marlite Panels (FED)",
  },
  {
    id: 10,
    foodName: "Wine - Tribal Sauvignon",
    price: 6330,
    img: "./10.png",
    categoryName: "Painting & Vinyl Wall Covering",
  },
  {
    id: 11,
    foodName: "Wine - Chenin Blanc K.w.v.",
    price: 4411,
    img: "./11.png",
    categoryName: "Electrical and Fire Alarm",
  },
  {
    id: 12,
    foodName: "English Muffin",
    price: 9563,
    img: "./12.png",
    categoryName: "Sitework & Site Utilities",
  },
  {
    id: 13,
    foodName: "Wine - Ice Wine",
    price: 9452,
    img: "./13.png",
    categoryName: "Soft Flooring and Base",
  },
  {
    id: 14,
    foodName: "Wine - Delicato Merlot",
    price: 7529,
    img: "./14.png",
    categoryName: "HVAC",
  },
  {
    id: 15,
    foodName: "Wine - Chateau Bonnet",
    price: 4157,
    img: "./15.png",
    categoryName: "Framing (Steel)",
  },
  {
    id: 16,
    foodName: "Cinnamon Rolls",
    price: 5851,
    img: "./16.png",
    categoryName: "Asphalt Paving",
  },
];
